# values/ebs-csi-driver.yaml
controller:
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
node:
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
