- name: Generate join command for a control node
  command: microk8s add-node
  register: control_join_output

- name: Extract control plane join command
  set_fact:
    current_control_plane_join_command: "{{ control_join_output.stdout_lines | select('match', '^microk8s join ') | list | first }}"

- name: Distribute join command to control node
  copy:
    content: "{{ current_control_plane_join_command }}"
    dest: /tmp/control-plane-join-command.txt
  delegate_to: "{{ item }}"

- name: Join control node to the cluster
  shell: |
    cat /tmp/control-plane-join-command.txt | bash
  delegate_to: "{{ item }}"
  register: join_result
  retries: 5          # Number of retry attempts
  delay: 10           # Delay (in seconds) between retries
  until: join_result.rc == 0  # Condition to check for success
